package discord_js.typings.index;

typedef ActionRowComponentOptions = ts.AnyOf7<InteractionButtonComponentData, LinkButtonComponentData, StringSelectMenuComponentData, UserSelectMenuComponentData, RoleSelectMenuComponentData, MentionableSelectMenuComponentData, ChannelSelectMenuComponentData>;