package discord_js.typings.index;

typedef ApplicationCommandData = ts.AnyOf4<UserApplicationCommandData, MessageApplicationCommandData, ChatInputApplicationCommandData, PrimaryEntryPointCommandData>;