package discord_js.typings.index;

typedef ClientEvents = {
	var applicationCommandPermissionsUpdate : ts.Tuple1<ApplicationCommandPermissionsUpdateData>;
	var autoModerationActionExecution : ts.Tuple1<AutoModerationActionExecution>;
	var autoModerationRuleCreate : ts.Tuple1<AutoModerationRule>;
	var autoModerationRuleDelete : ts.Tuple1<AutoModerationRule>;
	var autoModerationRuleUpdate : ts.Tuple2<Null<AutoModerationRule>, AutoModerationRule>;
	var cacheSweep : ts.Tuple1<String>;
	var channelCreate : ts.Tuple1<NonThreadGuildBasedChannel>;
	var channelDelete : ts.Tuple1<ts.AnyOf8<CategoryChannel, DMChannel, NewsChannel, StageChannel, TextChannel, VoiceChannel, ForumChannel, MediaChannel>>;
	var channelPinsUpdate : ts.Tuple2<TextBasedChannel, js.lib.Date>;
	var channelUpdate : ts.Tuple2<ts.AnyOf8<CategoryChannel, DMChannel, NewsChannel, StageChannel, TextChannel, VoiceChannel, ForumChannel, MediaChannel>, ts.AnyOf8<CategoryChannel, DMChannel, NewsChannel, StageChannel, TextChannel, VoiceChannel, ForumChannel, MediaChannel>>;
	var clientReady : ts.Tuple1<Client<Bool>>;
	var debug : ts.Tuple1<String>;
	var warn : ts.Tuple1<String>;
	var emojiCreate : ts.Tuple1<GuildEmoji>;
	var emojiDelete : ts.Tuple1<GuildEmoji>;
	var emojiUpdate : ts.Tuple2<GuildEmoji, GuildEmoji>;
	var entitlementCreate : ts.Tuple1<Entitlement>;
	var entitlementDelete : ts.Tuple1<Entitlement>;
	var entitlementUpdate : ts.Tuple2<Null<Entitlement>, Entitlement>;
	var error : ts.Tuple1<js.lib.Error>;
	var guildAuditLogEntryCreate : ts.Tuple2<GuildAuditLogsEntry<discord_api_types.v10.AuditLogEvent, String, String>, Guild>;
	var guildAvailable : ts.Tuple1<Guild>;
	var guildBanAdd : ts.Tuple1<GuildBan>;
	var guildBanRemove : ts.Tuple1<GuildBan>;
	var guildCreate : ts.Tuple1<Guild>;
	var guildDelete : ts.Tuple1<Guild>;
	var guildUnavailable : ts.Tuple1<Guild>;
	var guildIntegrationsUpdate : ts.Tuple1<Guild>;
	var guildMemberAdd : ts.Tuple1<GuildMember>;
	var guildMemberAvailable : ts.Tuple1<ts.AnyOf2<GuildMember, PartialGuildMember>>;
	var guildMemberRemove : ts.Tuple1<ts.AnyOf2<GuildMember, PartialGuildMember>>;
	var guildMembersChunk : ts.Tuple3<ReadonlyCollection<String, GuildMember>, Guild, GuildMembersChunk>;
	var guildMemberUpdate : ts.Tuple2<ts.AnyOf2<GuildMember, PartialGuildMember>, GuildMember>;
	var guildUpdate : ts.Tuple2<Guild, Guild>;
	var guildSoundboardSoundCreate : ts.Tuple1<GuildSoundboardSound>;
	var guildSoundboardSoundDelete : ts.Tuple1<ts.AnyOf2<GuildSoundboardSound, PartialSoundboardSound>>;
	var guildSoundboardSoundUpdate : ts.Tuple2<Null<GuildSoundboardSound>, GuildSoundboardSound>;
	var guildSoundboardSoundsUpdate : ts.Tuple2<ReadonlyCollection<String, GuildSoundboardSound>, Guild>;
	var inviteCreate : ts.Tuple1<Invite>;
	var inviteDelete : ts.Tuple1<Invite>;
	var messageCreate : ts.Tuple1<OmitPartialGroupDMChannel<Message<Bool>>>;
	var messageDelete : ts.Tuple1<OmitPartialGroupDMChannel<ts.AnyOf2<Message<Bool>, PartialMessage<Bool>>>>;
	var messagePollVoteAdd : ts.Tuple2<ts.AnyOf2<PollAnswer, PartialPollAnswer>, String>;
	var messagePollVoteRemove : ts.Tuple2<ts.AnyOf2<PollAnswer, PartialPollAnswer>, String>;
	var messageReactionRemoveAll : ts.Tuple2<OmitPartialGroupDMChannel<ts.AnyOf2<Message<Bool>, PartialMessage<Bool>>>, ReadonlyCollection<String, MessageReaction>>;
	var messageReactionRemoveEmoji : ts.Tuple1<ts.AnyOf2<MessageReaction, PartialMessageReaction>>;
	var messageDeleteBulk : ts.Tuple2<ReadonlyCollection<String, ts.AnyOf2<Message<Bool>, PartialMessage<Bool>>>, GuildTextBasedChannel>;
	var messageReactionAdd : ts.Tuple3<ts.AnyOf2<MessageReaction, PartialMessageReaction>, ts.AnyOf2<User, PartialUser>, MessageReactionEventDetails>;
	var messageReactionRemove : ts.Tuple3<ts.AnyOf2<MessageReaction, PartialMessageReaction>, ts.AnyOf2<User, PartialUser>, MessageReactionEventDetails>;
	var messageUpdate : ts.Tuple2<OmitPartialGroupDMChannel<ts.AnyOf2<Message<Bool>, PartialMessage<Bool>>>, OmitPartialGroupDMChannel<Message<Bool>>>;
	var presenceUpdate : ts.Tuple2<Null<Presence>, Presence>;
	var ready : ts.Tuple1<Client<Bool>>;
	var invalidated : std.Array<Any>;
	var roleCreate : ts.Tuple1<Role>;
	var roleDelete : ts.Tuple1<Role>;
	var roleUpdate : ts.Tuple2<Role, Role>;
	var threadCreate : ts.Tuple2<AnyThreadChannel, Bool>;
	var threadDelete : ts.Tuple1<AnyThreadChannel>;
	var threadListSync : ts.Tuple2<ReadonlyCollection<String, AnyThreadChannel>, Guild>;
	var threadMemberUpdate : ts.Tuple2<ThreadMember<Bool>, ThreadMember<Bool>>;
	var threadMembersUpdate : ts.Tuple3<ReadonlyCollection<String, ThreadMember<Bool>>, ReadonlyCollection<String, ts.AnyOf2<ThreadMember<Bool>, PartialThreadMember>>, AnyThreadChannel>;
	var threadUpdate : ts.Tuple2<AnyThreadChannel, AnyThreadChannel>;
	var typingStart : ts.Tuple1<Typing>;
	var userUpdate : ts.Tuple2<ts.AnyOf2<User, PartialUser>, User>;
	var voiceChannelEffectSend : ts.Tuple1<VoiceChannelEffect>;
	var voiceStateUpdate : ts.Tuple2<VoiceState, VoiceState>;
	var webhookUpdate : ts.Tuple1<ts.AnyOf5<NewsChannel, TextChannel, VoiceChannel, ForumChannel, MediaChannel>>;
	var webhooksUpdate : ts.Tuple1<ts.AnyOf5<NewsChannel, TextChannel, VoiceChannel, ForumChannel, MediaChannel>>;
	var interactionCreate : ts.Tuple1<Interaction<CacheType>>;
	var shardDisconnect : ts.Tuple2<CloseEvent, Float>;
	var shardError : ts.Tuple2<js.lib.Error, Float>;
	var shardReady : ts.Tuple2<Float, Null<js.lib.Set<String>>>;
	var shardReconnecting : ts.Tuple1<Float>;
	var shardResume : ts.Tuple2<Float, Float>;
	var stageInstanceCreate : ts.Tuple1<StageInstance>;
	var stageInstanceUpdate : ts.Tuple2<Null<StageInstance>, StageInstance>;
	var stageInstanceDelete : ts.Tuple1<StageInstance>;
	var stickerCreate : ts.Tuple1<Sticker>;
	var stickerDelete : ts.Tuple1<Sticker>;
	var stickerUpdate : ts.Tuple2<Sticker, Sticker>;
	var subscriptionCreate : ts.Tuple1<Subscription>;
	var subscriptionDelete : ts.Tuple1<Subscription>;
	var subscriptionUpdate : ts.Tuple2<Null<Subscription>, Subscription>;
	var guildScheduledEventCreate : ts.Tuple1<GuildScheduledEvent<discord_api_types.v10.GuildScheduledEventStatus>>;
	var guildScheduledEventUpdate : ts.Tuple2<Null<ts.AnyOf2<GuildScheduledEvent<discord_api_types.v10.GuildScheduledEventStatus>, PartialGuildScheduledEvent>>, GuildScheduledEvent<discord_api_types.v10.GuildScheduledEventStatus>>;
	var guildScheduledEventDelete : ts.Tuple1<ts.AnyOf2<GuildScheduledEvent<discord_api_types.v10.GuildScheduledEventStatus>, PartialGuildScheduledEvent>>;
	var guildScheduledEventUserAdd : ts.Tuple2<ts.AnyOf2<GuildScheduledEvent<discord_api_types.v10.GuildScheduledEventStatus>, PartialGuildScheduledEvent>, User>;
	var guildScheduledEventUserRemove : ts.Tuple2<ts.AnyOf2<GuildScheduledEvent<discord_api_types.v10.GuildScheduledEventStatus>, PartialGuildScheduledEvent>, User>;
	var soundboardSounds : ts.Tuple2<ReadonlyCollection<String, GuildSoundboardSound>, Guild>;
};