package discord_js.typings.index;

typedef ComponentInLabelData = ts.AnyOf7<StringSelectMenuComponentData, UserSelectMenuComponentData, RoleSelectMenuComponentData, MentionableSelectMenuComponentData, ChannelSelectMenuComponentData, TextInputComponentData, FileUploadComponentData>;