package discord_js.typings.index;

@:jsRequire("discord.js/typings/index", "Guild") extern class Guild extends AnonymousGuild {
	private function new(client:Client<Bool>, data:discord_js.typings.rawdatatypes.RawGuildData);
	private function _sortedRoles():Collection<String, Role>;
	private function _sortedChannels(channel:NonThreadGuildBasedChannel):Collection<String, NonThreadGuildBasedChannel>;
	public final afkChannel : Null<VoiceChannel>;
	public var afkChannelId : Null<String>;
	public var afkTimeout : Float;
	public var applicationId : Null<String>;
	public var maxVideoChannelUsers : Null<Float>;
	public var approximateMemberCount : Null<Float>;
	public var approximatePresenceCount : Null<Float>;
	public var autoModerationRules : AutoModerationRuleManager;
	public var available : Bool;
	public var bans : GuildBanManager;
	public var channels : GuildChannelManager;
	public var commands : GuildApplicationCommandManager;
	public var defaultMessageNotifications : discord_api_types.v10.GuildDefaultMessageNotifications;
	public var discoverySplash : Null<String>;
	public var emojis : GuildEmojiManager;
	public var explicitContentFilter : discord_api_types.v10.GuildExplicitContentFilter;
	public var invites : GuildInviteManager;
	public final joinedAt : js.lib.Date;
	public var joinedTimestamp : Float;
	public var large : Bool;
	public var maximumMembers : Null<Float>;
	public var maximumPresences : Null<Float>;
	public var maxStageVideoChannelUsers : Null<Float>;
	public var memberCount : Float;
	public var members : GuildMemberManager;
	public var mfaLevel : discord_api_types.v10.GuildMFALevel;
	public var ownerId : String;
	public var preferredLocale : discord_api_types.v10.Locale;
	public var premiumProgressBarEnabled : Bool;
	public var premiumTier : discord_api_types.v10.GuildPremiumTier;
	public var presences : PresenceManager;
	public final publicUpdatesChannel : Null<TextChannel>;
	public var publicUpdatesChannelId : Null<String>;
	public var roles : RoleManager;
	public final rulesChannel : Null<TextChannel>;
	public var rulesChannelId : Null<String>;
	public final safetyAlertsChannel : Null<TextChannel>;
	public var safetyAlertsChannelId : Null<String>;
	public var scheduledEvents : GuildScheduledEventManager;
	public final shard : WebSocketShard;
	public var shardId : Float;
	public var soundboardSounds : GuildSoundboardSoundManager;
	public var stageInstances : StageInstanceManager;
	public var stickers : GuildStickerManager;
	public var incidentsData : Null<IncidentActions>;
	public final systemChannel : Null<TextChannel>;
	public var systemChannelFlags : {
		var bitfield : Dynamic;
		var add : Dynamic;
		var any : Dynamic;
		var equals : Dynamic;
		var freeze : Dynamic;
		var has : Dynamic;
		var missing : Dynamic;
		var remove : Dynamic;
		var serialize : Dynamic;
		var toArray : Dynamic;
		var toJSON : Dynamic;
		var valueOf : Dynamic;
	};
	public var systemChannelId : Null<String>;
	public var vanityURLUses : Null<Float>;
	public dynamic function voiceAdapterCreator(methods:InternalDiscordGatewayAdapterLibraryMethods):InternalDiscordGatewayAdapterImplementerMethods;
	public var voiceStates : VoiceStateManager;
	public final widgetChannel : Null<ts.AnyOf6<NewsChannel, StageChannel, TextChannel, VoiceChannel, ForumChannel, MediaChannel>>;
	public var widgetChannelId : Null<String>;
	public var widgetEnabled : Null<Bool>;
	public final maximumBitrate : Float;
	public function createTemplate(name:String, ?description:String):js.lib.Promise<GuildTemplate>;
	public function delete():js.lib.Promise<Guild>;
	public function discoverySplashURL(?options:ImageURLOptions):Null<String>;
	public function edit(options:GuildEditOptions):js.lib.Promise<Guild>;
	public function editOnboarding(options:GuildOnboardingEditOptions):js.lib.Promise<GuildOnboarding>;
	public function editWelcomeScreen(options:WelcomeScreenEditOptions):js.lib.Promise<WelcomeScreen>;
	public function equals(guild:Guild):Bool;
	public function fetchAuditLogs<Event>(?options:GuildAuditLogsFetchOptions<Event>):js.lib.Promise<GuildAuditLogs<Dynamic>>;
	public function fetchIntegrations():js.lib.Promise<Collection<String, Integration>>;
	public function fetchOnboarding():js.lib.Promise<GuildOnboarding>;
	public function fetchOwner(?options:BaseFetchOptions):js.lib.Promise<GuildMember>;
	public function fetchPreview():js.lib.Promise<GuildPreview>;
	public function fetchTemplates():js.lib.Promise<Collection<String, GuildTemplate>>;
	public function fetchVanityData():js.lib.Promise<Vanity>;
	public function fetchWebhooks():js.lib.Promise<Collection<String, Webhook<Int>>>;
	public function fetchWelcomeScreen():js.lib.Promise<WelcomeScreen>;
	public function fetchWidget():js.lib.Promise<Widget>;
	public function fetchWidgetSettings():js.lib.Promise<GuildWidgetSettings>;
	public function widgetImageURL(?style:discord_api_types.v10.GuildWidgetStyle):String;
	public function leave():js.lib.Promise<Guild>;
	public function disableInvites(?disabled:Bool):js.lib.Promise<Guild>;
	public function setIncidentActions(incidentActions:IncidentActionsEditOptions):js.lib.Promise<IncidentActions>;
	public function setAFKChannel(afkChannel:Null<VoiceChannelResolvable>, ?reason:String):js.lib.Promise<Guild>;
	public function setAFKTimeout(afkTimeout:Float, ?reason:String):js.lib.Promise<Guild>;
	public function setBanner(banner:Null<ts.AnyOf2<String, global.Buffer>>, ?reason:String):js.lib.Promise<Guild>;
	public function setDefaultMessageNotifications(defaultMessageNotifications:Null<discord_api_types.v10.GuildDefaultMessageNotifications>, ?reason:String):js.lib.Promise<Guild>;
	public function setDiscoverySplash(discoverySplash:Null<ts.AnyOf2<String, global.Buffer>>, ?reason:String):js.lib.Promise<Guild>;
	public function setExplicitContentFilter(explicitContentFilter:Null<discord_api_types.v10.GuildExplicitContentFilter>, ?reason:String):js.lib.Promise<Guild>;
	public function setIcon(icon:Null<ts.AnyOf2<String, global.Buffer>>, ?reason:String):js.lib.Promise<Guild>;
	public function setName(name:String, ?reason:String):js.lib.Promise<Guild>;
	public function setOwner(owner:GuildMemberResolvable, ?reason:String):js.lib.Promise<Guild>;
	public function setPreferredLocale(preferredLocale:Null<discord_api_types.v10.Locale>, ?reason:String):js.lib.Promise<Guild>;
	public function setPublicUpdatesChannel(publicUpdatesChannel:Null<TextChannelResolvable>, ?reason:String):js.lib.Promise<Guild>;
	public function setRulesChannel(rulesChannel:Null<TextChannelResolvable>, ?reason:String):js.lib.Promise<Guild>;
	public function setSafetyAlertsChannel(safetyAlertsChannel:Null<TextChannelResolvable>, ?reason:String):js.lib.Promise<Guild>;
	public function setSplash(splash:Null<ts.AnyOf2<String, global.Buffer>>, ?reason:String):js.lib.Promise<Guild>;
	public function setSystemChannel(systemChannel:Null<TextChannelResolvable>, ?reason:String):js.lib.Promise<Guild>;
	public function setSystemChannelFlags(systemChannelFlags:SystemChannelFlagsResolvable, ?reason:String):js.lib.Promise<Guild>;
	public function setVerificationLevel(verificationLevel:Null<discord_api_types.v10.GuildVerificationLevel>, ?reason:String):js.lib.Promise<Guild>;
	public function setPremiumProgressBarEnabled(?enabled:Bool, ?reason:String):js.lib.Promise<Guild>;
	public function setWidgetSettings(settings:GuildWidgetSettingsData, ?reason:String):js.lib.Promise<Guild>;
	public function setMFALevel(level:discord_api_types.v10.GuildMFALevel, ?reason:String):js.lib.Promise<Guild>;
	public function toJSON():Any;
	static var prototype : Guild;
}