package discord_js.typings.index;

typedef IBaseGuildVoiceChannel = {
	var bitrate : Float;
	final full : Bool;
	final joinable : Bool;
	final members : Collection<String, GuildMember>;
	var nsfw : Bool;
	var rateLimitPerUser : Null<Float>;
	var rtcRegion : Null<String>;
	var userLimit : Float;
	var videoQualityMode : Null<discord_api_types.v10.VideoQualityMode>;
	function createInvite(?options:InviteCreateOptions):js.lib.Promise<Invite>;
	function fetchInvites(?cache:Bool):js.lib.Promise<Collection<String, Invite>>;
	function setBitrate(bitrate:Float, ?reason:String):js.lib.Promise<BaseGuildVoiceChannel>;
	function setRTCRegion(rtcRegion:Null<String>, ?reason:String):js.lib.Promise<BaseGuildVoiceChannel>;
	function setUserLimit(userLimit:Float, ?reason:String):js.lib.Promise<BaseGuildVoiceChannel>;
	function setVideoQualityMode(videoQualityMode:discord_api_types.v10.VideoQualityMode, ?reason:String):js.lib.Promise<BaseGuildVoiceChannel>;
	function memberPermissions(member:GuildMember, checkAdmin:Bool):{
		var any : Dynamic;
		var has : Dynamic;
		var missing : Dynamic;
		var serialize : Dynamic;
		var toArray : Dynamic;
		var bitfield : Dynamic;
		var add : Dynamic;
		var equals : Dynamic;
		var freeze : Dynamic;
		var remove : Dynamic;
		var toJSON : Dynamic;
		var valueOf : Dynamic;
	};
	function rolePermissions(role:Role, checkAdmin:Bool):{
		var any : Dynamic;
		var has : Dynamic;
		var missing : Dynamic;
		var serialize : Dynamic;
		var toArray : Dynamic;
		var bitfield : Dynamic;
		var add : Dynamic;
		var equals : Dynamic;
		var freeze : Dynamic;
		var remove : Dynamic;
		var toJSON : Dynamic;
		var valueOf : Dynamic;
	};
	final createdAt : js.lib.Date;
	final createdTimestamp : Float;
	final deletable : Bool;
	var flags : {
		var bitfield : Dynamic;
		var add : Dynamic;
		var any : Dynamic;
		var equals : Dynamic;
		var freeze : Dynamic;
		var has : Dynamic;
		var missing : Dynamic;
		var remove : Dynamic;
		var serialize : Dynamic;
		var toArray : Dynamic;
		var toJSON : Dynamic;
		var valueOf : Dynamic;
	};
	var guild : Guild;
	var guildId : String;
	final manageable : Bool;
	var name : String;
	final parent : Null<CategoryChannel>;
	var parentId : Null<String>;
	var permissionOverwrites : PermissionOverwriteManager;
	final permissionsLocked : Null<Bool>;
	final position : Float;
	var rawPosition : Float;
	var type : GuildChannelTypes;
	final viewable : Bool;
	function clone(?options:GuildChannelCloneOptions):js.lib.Promise<BaseGuildVoiceChannel>;
	function delete(?reason:String):js.lib.Promise<BaseGuildVoiceChannel>;
	function edit(options:GuildChannelEditOptions):js.lib.Promise<BaseGuildVoiceChannel>;
	function equals(channel:GuildChannel):Bool;
	function lockPermissions():js.lib.Promise<BaseGuildVoiceChannel>;
	@:overload(function(memberOrRole:ts.AnyOf6<String, User, GuildMember, Role, Message<Bool>, ThreadMember<Bool>>, ?checkAdmin:Bool):Null<{
		var any : Dynamic;
		var has : Dynamic;
		var missing : Dynamic;
		var serialize : Dynamic;
		var toArray : Dynamic;
		var bitfield : Dynamic;
		var add : Dynamic;
		var equals : Dynamic;
		var freeze : Dynamic;
		var remove : Dynamic;
		var toJSON : Dynamic;
		var valueOf : Dynamic;
	}> { })
	function permissionsFor(memberOrRole:ts.AnyOf2<GuildMember, Role>, ?checkAdmin:Bool):{
		var any : Dynamic;
		var has : Dynamic;
		var missing : Dynamic;
		var serialize : Dynamic;
		var toArray : Dynamic;
		var bitfield : Dynamic;
		var add : Dynamic;
		var equals : Dynamic;
		var freeze : Dynamic;
		var remove : Dynamic;
		var toJSON : Dynamic;
		var valueOf : Dynamic;
	};
	function setName(name:String, ?reason:String):js.lib.Promise<BaseGuildVoiceChannel>;
	function setParent(channel:Null<CategoryChannelResolvable>, ?options:SetParentOptions):js.lib.Promise<BaseGuildVoiceChannel>;
	function setPosition(position:Float, ?options:SetChannelPositionOptions):js.lib.Promise<BaseGuildVoiceChannel>;
	function isTextBased():Bool;
	/**
		Returns a string representation of an object.
	**/
	function toString():Dynamic;
	var id : String;
	final partial : Bool;
	final url : String;
	function fetch(?force:Bool):js.lib.Promise<BaseGuildVoiceChannel>;
	function isThread():Bool;
	function isDMBased():Bool;
	function isVoiceBased():Bool;
	function isThreadOnly():Bool;
	function isSendable():Bool;
	final client : Client<Bool>;
	function toJSON(props:haxe.extern.Rest<haxe.DynamicAccess<ts.AnyOf2<String, Bool>>>):Any;
	function valueOf():String;
	var messages : Dynamic;
	var bulkDelete : Dynamic;
	var fetchWebhooks : Dynamic;
	var createWebhook : Dynamic;
	var setRateLimitPerUser : Dynamic;
	var setNSFW : Dynamic;
	var lastMessageId : Dynamic;
	var lastMessage : Dynamic;
	var awaitMessageComponent : Dynamic;
	var awaitMessages : Dynamic;
	var createMessageComponentCollector : Dynamic;
	var createMessageCollector : Dynamic;
	var sendTyping : Dynamic;
	var send : Dynamic;
};