package discord_js.typings.index;

typedef IGuildMember = {
	var _roles : Array<String>;
	var avatar : Null<String>;
	var avatarDecorationData : Null<AvatarDecorationData>;
	var banner : Null<String>;
	final bannable : Bool;
	final dmChannel : Null<DMChannel>;
	final displayColor : Float;
	final displayHexColor : Dynamic;
	final displayName : String;
	var guild : Guild;
	final id : String;
	var pending : Bool;
	final communicationDisabledUntil : Null<js.lib.Date>;
	var communicationDisabledUntilTimestamp : Null<Float>;
	var flags : {
		var bitfield : Dynamic;
		var add : Dynamic;
		var any : Dynamic;
		var equals : Dynamic;
		var freeze : Dynamic;
		var has : Dynamic;
		var missing : Dynamic;
		var remove : Dynamic;
		var serialize : Dynamic;
		var toArray : Dynamic;
		var toJSON : Dynamic;
		var valueOf : Dynamic;
	};
	final joinedAt : Null<js.lib.Date>;
	var joinedTimestamp : Null<Float>;
	final kickable : Bool;
	final manageable : Bool;
	final moderatable : Bool;
	var nickname : Null<String>;
	final partial : Bool;
	final permissions : {
		var any : Dynamic;
		var has : Dynamic;
		var missing : Dynamic;
		var serialize : Dynamic;
		var toArray : Dynamic;
		var bitfield : Dynamic;
		var add : Dynamic;
		var equals : Dynamic;
		var freeze : Dynamic;
		var remove : Dynamic;
		var toJSON : Dynamic;
		var valueOf : Dynamic;
	};
	final premiumSince : Null<js.lib.Date>;
	var premiumSinceTimestamp : Null<Float>;
	final presence : Null<Presence>;
	final roles : GuildMemberRoleManager;
	var user : User;
	final voice : VoiceState;
	function avatarURL(?options:ImageURLOptions):Null<String>;
	function avatarDecorationURL():Null<String>;
	function bannerURL(?options:ImageURLOptions):Null<String>;
	function ban(?options:BanOptions):js.lib.Promise<GuildMember>;
	function disableCommunicationUntil(timeout:Null<DateResolvable>, ?reason:String):js.lib.Promise<GuildMember>;
	function timeout(timeout:Null<Float>, ?reason:String):js.lib.Promise<GuildMember>;
	function fetch(?force:Bool):js.lib.Promise<GuildMember>;
	function createDM(?force:Bool):js.lib.Promise<DMChannel>;
	function deleteDM():js.lib.Promise<DMChannel>;
	function displayAvatarURL(?options:ImageURLOptions):String;
	function displayBannerURL(?options:ImageURLOptions):Null<String>;
	function displayAvatarDecorationURL():Null<String>;
	function edit(options:GuildMemberEditOptions):js.lib.Promise<GuildMember>;
	function isCommunicationDisabled():Bool;
	function kick(?reason:String):js.lib.Promise<GuildMember>;
	function permissionsIn(channel:GuildChannelResolvable):{
		var any : Dynamic;
		var has : Dynamic;
		var missing : Dynamic;
		var serialize : Dynamic;
		var toArray : Dynamic;
		var bitfield : Dynamic;
		var add : Dynamic;
		var equals : Dynamic;
		var freeze : Dynamic;
		var remove : Dynamic;
		var toJSON : Dynamic;
		var valueOf : Dynamic;
	};
	function setFlags(flags:GuildMemberFlagsResolvable, ?reason:String):js.lib.Promise<GuildMember>;
	function setNickname(nickname:Null<String>, ?reason:String):js.lib.Promise<GuildMember>;
	function toJSON():Any;
	/**
		Returns a string representation of an object.
	**/
	function toString():Dynamic;
	function valueOf():String;
	final client : Client<Bool>;
	function send(options:ts.AnyOf3<String, MessagePayload, MessageCreateOptions>):js.lib.Promise<Message<Bool>>;
};