package discord_js.typings.index;

typedef IThreadOnlyChannel = {
	var type : Int;
	var threads : GuildForumThreadManager;
	var availableTags : Array<GuildForumTag>;
	var defaultReactionEmoji : Null<DefaultReactionEmoji>;
	var defaultThreadRateLimitPerUser : Null<Float>;
	var rateLimitPerUser : Null<Float>;
	var defaultAutoArchiveDuration : Null<discord_api_types.v10.ThreadAutoArchiveDuration>;
	var nsfw : Bool;
	var topic : Null<String>;
	var defaultSortOrder : Null<discord_api_types.v10.SortOrderType>;
	function setAvailableTags(tags:haxe.ds.ReadOnlyArray<GuildForumTagData>, ?reason:String):js.lib.Promise<ThreadOnlyChannel>;
	function setDefaultReactionEmoji(emojiId:Null<DefaultReactionEmoji>, ?reason:String):js.lib.Promise<ThreadOnlyChannel>;
	function setDefaultThreadRateLimitPerUser(rateLimit:Float, ?reason:String):js.lib.Promise<ThreadOnlyChannel>;
	function createInvite(?options:InviteCreateOptions):js.lib.Promise<Invite>;
	function fetchInvites(?cache:Bool):js.lib.Promise<Collection<String, Invite>>;
	function setDefaultAutoArchiveDuration(defaultAutoArchiveDuration:discord_api_types.v10.ThreadAutoArchiveDuration, ?reason:String):js.lib.Promise<ThreadOnlyChannel>;
	function setTopic(topic:Null<String>, ?reason:String):js.lib.Promise<ThreadOnlyChannel>;
	function setDefaultSortOrder(defaultSortOrder:Null<discord_api_types.v10.SortOrderType>, ?reason:String):js.lib.Promise<ThreadOnlyChannel>;
	function memberPermissions(member:GuildMember, checkAdmin:Bool):{
		var any : Dynamic;
		var has : Dynamic;
		var missing : Dynamic;
		var serialize : Dynamic;
		var toArray : Dynamic;
		var bitfield : Dynamic;
		var add : Dynamic;
		var equals : Dynamic;
		var freeze : Dynamic;
		var remove : Dynamic;
		var toJSON : Dynamic;
		var valueOf : Dynamic;
	};
	function rolePermissions(role:Role, checkAdmin:Bool):{
		var any : Dynamic;
		var has : Dynamic;
		var missing : Dynamic;
		var serialize : Dynamic;
		var toArray : Dynamic;
		var bitfield : Dynamic;
		var add : Dynamic;
		var equals : Dynamic;
		var freeze : Dynamic;
		var remove : Dynamic;
		var toJSON : Dynamic;
		var valueOf : Dynamic;
	};
	final createdAt : js.lib.Date;
	final createdTimestamp : Float;
	final deletable : Bool;
	var flags : {
		var bitfield : Dynamic;
		var add : Dynamic;
		var any : Dynamic;
		var equals : Dynamic;
		var freeze : Dynamic;
		var has : Dynamic;
		var missing : Dynamic;
		var remove : Dynamic;
		var serialize : Dynamic;
		var toArray : Dynamic;
		var toJSON : Dynamic;
		var valueOf : Dynamic;
	};
	var guild : Guild;
	var guildId : String;
	final manageable : Bool;
	final members : Collection<String, GuildMember>;
	var name : String;
	final parent : Null<CategoryChannel>;
	var parentId : Null<String>;
	var permissionOverwrites : PermissionOverwriteManager;
	final permissionsLocked : Null<Bool>;
	final position : Float;
	var rawPosition : Float;
	final viewable : Bool;
	function clone(?options:GuildChannelCloneOptions):js.lib.Promise<ThreadOnlyChannel>;
	function delete(?reason:String):js.lib.Promise<ThreadOnlyChannel>;
	function edit(options:GuildChannelEditOptions):js.lib.Promise<ThreadOnlyChannel>;
	function equals(channel:GuildChannel):Bool;
	function lockPermissions():js.lib.Promise<ThreadOnlyChannel>;
	@:overload(function(memberOrRole:ts.AnyOf6<String, User, GuildMember, Role, Message<Bool>, ThreadMember<Bool>>, ?checkAdmin:Bool):Null<{
		var any : Dynamic;
		var has : Dynamic;
		var missing : Dynamic;
		var serialize : Dynamic;
		var toArray : Dynamic;
		var bitfield : Dynamic;
		var add : Dynamic;
		var equals : Dynamic;
		var freeze : Dynamic;
		var remove : Dynamic;
		var toJSON : Dynamic;
		var valueOf : Dynamic;
	}> { })
	function permissionsFor(memberOrRole:ts.AnyOf2<GuildMember, Role>, ?checkAdmin:Bool):{
		var any : Dynamic;
		var has : Dynamic;
		var missing : Dynamic;
		var serialize : Dynamic;
		var toArray : Dynamic;
		var bitfield : Dynamic;
		var add : Dynamic;
		var equals : Dynamic;
		var freeze : Dynamic;
		var remove : Dynamic;
		var toJSON : Dynamic;
		var valueOf : Dynamic;
	};
	function setName(name:String, ?reason:String):js.lib.Promise<ThreadOnlyChannel>;
	function setParent(channel:Null<CategoryChannelResolvable>, ?options:SetParentOptions):js.lib.Promise<ThreadOnlyChannel>;
	function setPosition(position:Float, ?options:SetChannelPositionOptions):js.lib.Promise<ThreadOnlyChannel>;
	function isTextBased():Bool;
	/**
		Returns a string representation of an object.
	**/
	function toString():Dynamic;
	var id : String;
	final partial : Bool;
	final url : String;
	function fetch(?force:Bool):js.lib.Promise<ThreadOnlyChannel>;
	function isThread():Bool;
	function isDMBased():Bool;
	function isVoiceBased():Bool;
	function isThreadOnly():Bool;
	function isSendable():Bool;
	final client : Client<Bool>;
	function toJSON(props:haxe.extern.Rest<haxe.DynamicAccess<ts.AnyOf2<String, Bool>>>):Any;
	function valueOf():String;
	var fetchWebhooks : Dynamic;
	var createWebhook : Dynamic;
	var setRateLimitPerUser : Dynamic;
	var setNSFW : Dynamic;
	var lastMessageId : Dynamic;
	var lastPinTimestamp : Dynamic;
};