package discord_js.typings.index;

@:jsRequire("discord.js/typings/index", "Message") extern class Message<InGuild> extends Base {
	private function new(client:Client<Bool>, data:discord_api_types.v10.APIMessage);
	private final _cacheType : InGuild;
	private function _patch(data:ts.AnyOf2<discord_api_types.v10.APIMessage, discord_api_types.v10.GatewayMessageUpdateDispatchData>):Void;
	public var activity : Null<MessageActivity>;
	public var applicationId : Null<String>;
	public var attachments : Collection<String, Attachment>;
	public var author : User;
	public final bulkDeletable : Bool;
	public final channel : If<InGuild, GuildTextBasedChannel, TextBasedChannel>;
	public var channelId : String;
	public final cleanContent : String;
	public var components : Array<TopLevelComponent>;
	public var content : String;
	public final createdAt : js.lib.Date;
	public var createdTimestamp : Float;
	public final crosspostable : Bool;
	public final deletable : Bool;
	public final editable : Bool;
	public final editedAt : Null<js.lib.Date>;
	public var editedTimestamp : Null<Float>;
	public var embeds : Array<Embed>;
	public var groupActivityApplication : Null<ClientApplication>;
	public var guildId : If<InGuild, String, Dynamic>;
	public final guild : If<InGuild, Guild, Dynamic>;
	public final hasThread : Bool;
	public var id : String;
	public var interaction : Null<MessageInteraction>;
	public var interactionMetadata : Null<MessageInteractionMetadata>;
	public final member : Null<GuildMember>;
	public var mentions : MessageMentions<InGuild>;
	public var nonce : Null<ts.AnyOf2<String, Float>>;
	public final partial : Bool;
	public final pinnable : Bool;
	public var pinned : Bool;
	public var reactions : ReactionManager;
	public var stickers : Collection<String, Sticker>;
	public var position : Null<Float>;
	public var roleSubscriptionData : Null<RoleSubscriptionData>;
	public var resolved : Null<CommandInteractionResolvedData<CacheType>>;
	public var system : Bool;
	public final thread : Null<AnyThreadChannel>;
	public var tts : Bool;
	public var poll : Null<Poll>;
	public var call : Null<MessageCall>;
	public var type : discord_api_types.v10.MessageType;
	public final url : String;
	public var webhookId : Null<String>;
	public var flags : {
		var bitfield : Dynamic;
		var add : Dynamic;
		var any : Dynamic;
		var equals : Dynamic;
		var freeze : Dynamic;
		var has : Dynamic;
		var missing : Dynamic;
		var remove : Dynamic;
		var serialize : Dynamic;
		var toArray : Dynamic;
		var toJSON : Dynamic;
		var valueOf : Dynamic;
	};
	public var reference : Null<MessageReference>;
	public var messageSnapshots : Collection<String, MessageSnapshot>;
	public function awaitMessageComponent<ComponentType>(?options:AwaitMessageCollectorOptionsParams<ComponentType, InGuild>):js.lib.Promise<Dynamic>;
	public function awaitReactions(?options:AwaitReactionsOptions):js.lib.Promise<Collection<String, MessageReaction>>;
	public function createReactionCollector(?options:ReactionCollectorOptions):ReactionCollector;
	public function createMessageComponentCollector<ComponentType>(?options:MessageCollectorOptionsParams<ComponentType, InGuild>):InteractionCollector<Dynamic>;
	public function delete():js.lib.Promise<OmitPartialGroupDMChannel<Message<InGuild>>>;
	public function edit(content:ts.AnyOf3<String, MessagePayload, MessageEditOptions>):js.lib.Promise<OmitPartialGroupDMChannel<Message<InGuild>>>;
	public function equals(message:Message<Bool>, rawData:Any):Bool;
	public function fetchReference():js.lib.Promise<OmitPartialGroupDMChannel<Message<InGuild>>>;
	public function fetchWebhook():js.lib.Promise<Webhook<discord_api_types.v10.WebhookType>>;
	public function crosspost():js.lib.Promise<OmitPartialGroupDMChannel<Message<InGuild>>>;
	public function fetch(?force:Bool):js.lib.Promise<OmitPartialGroupDMChannel<Message<InGuild>>>;
	public function pin(?reason:String):js.lib.Promise<OmitPartialGroupDMChannel<Message<InGuild>>>;
	public function react(emoji:EmojiIdentifierResolvable):js.lib.Promise<MessageReaction>;
	public function removeAttachments():js.lib.Promise<OmitPartialGroupDMChannel<Message<InGuild>>>;
	public function reply(options:ts.AnyOf3<String, MessagePayload, MessageReplyOptions>):js.lib.Promise<OmitPartialGroupDMChannel<Message<InGuild>>>;
	public function forward(channel:ts.AnyOf9<String, DMChannel, PartialDMChannel, NewsChannel, StageChannel, TextChannel, PublicThreadChannel<Bool>, PrivateThreadChannel, VoiceChannel>):js.lib.Promise<Message<Bool>>;
	public function resolveComponent(customId:String):Null<MessageActionRowComponent>;
	public function startThread(options:StartThreadOptions):js.lib.Promise<PublicThreadChannel<Bool>>;
	public function suppressEmbeds(?suppress:Bool):js.lib.Promise<OmitPartialGroupDMChannel<Message<InGuild>>>;
	public function toJSON():Any;
	/**
		Returns a string representation of an object.
	**/
	public function toString():String;
	public function unpin(?reason:String):js.lib.Promise<OmitPartialGroupDMChannel<Message<InGuild>>>;
	public function inGuild():Bool;
	static var prototype : Message<Dynamic>;
}