package discord_js.typings.index;

typedef PublicThreadChannel<Forum> = {
	var type : Int;
	var archived : Null<Bool>;
	final archivedAt : Null<js.lib.Date>;
	var archiveTimestamp : Null<Float>;
	final createdAt : Null<js.lib.Date>;
	var _createdTimestamp : Null<Float>;
	final createdTimestamp : Null<Float>;
	var autoArchiveDuration : Null<discord_api_types.v10.ThreadAutoArchiveDuration>;
	final editable : Bool;
	var flags : {
		var bitfield : Dynamic;
		var add : Dynamic;
		var any : Dynamic;
		var equals : Dynamic;
		var freeze : Dynamic;
		var has : Dynamic;
		var missing : Dynamic;
		var remove : Dynamic;
		var serialize : Dynamic;
		var toArray : Dynamic;
		var toJSON : Dynamic;
		var valueOf : Dynamic;
	};
	var guild : Guild;
	var guildId : String;
	final guildMembers : Collection<String, GuildMember>;
	var invitable : Null<Bool>;
	final joinable : Bool;
	final joined : Bool;
	var locked : Null<Bool>;
	final manageable : Bool;
	final viewable : Bool;
	final sendable : Bool;
	var memberCount : Null<Float>;
	var messageCount : Null<Float>;
	var appliedTags : Array<String>;
	var totalMessageSent : Null<Float>;
	var members : ThreadMemberManager;
	var name : String;
	var ownerId : String;
	final parent : Null<If<Forum, ts.AnyOf2<ForumChannel, MediaChannel>, ts.AnyOf2<NewsChannel, TextChannel>>>;
	var parentId : Null<String>;
	var rateLimitPerUser : Null<Float>;
	final unarchivable : Bool;
	function delete(?reason:String):js.lib.Promise<PublicThreadChannel<Forum>>;
	function edit(options:ThreadEditOptions):js.lib.Promise<PublicThreadChannel<Forum>>;
	function join():js.lib.Promise<PublicThreadChannel<Forum>>;
	function leave():js.lib.Promise<PublicThreadChannel<Forum>>;
	@:overload(function(memberOrRole:ts.AnyOf6<String, User, GuildMember, Role, Message<Bool>, ThreadMember<Bool>>, ?checkAdmin:Bool):Null<{
		var any : Dynamic;
		var has : Dynamic;
		var missing : Dynamic;
		var serialize : Dynamic;
		var toArray : Dynamic;
		var bitfield : Dynamic;
		var add : Dynamic;
		var equals : Dynamic;
		var freeze : Dynamic;
		var remove : Dynamic;
		var toJSON : Dynamic;
		var valueOf : Dynamic;
	}> { })
	function permissionsFor(memberOrRole:ts.AnyOf2<GuildMember, Role>, ?checkAdmin:Bool):{
		var any : Dynamic;
		var has : Dynamic;
		var missing : Dynamic;
		var serialize : Dynamic;
		var toArray : Dynamic;
		var bitfield : Dynamic;
		var add : Dynamic;
		var equals : Dynamic;
		var freeze : Dynamic;
		var remove : Dynamic;
		var toJSON : Dynamic;
		var valueOf : Dynamic;
	};
	function fetchOwner(?options:FetchThreadOwnerOptions):js.lib.Promise<Null<ThreadMember<Bool>>>;
	function fetchStarterMessage(?options:BaseFetchOptions):js.lib.Promise<Null<Message<Bool>>>;
	function setArchived(?archived:Bool, ?reason:String):js.lib.Promise<PublicThreadChannel<Forum>>;
	function setAutoArchiveDuration(autoArchiveDuration:discord_api_types.v10.ThreadAutoArchiveDuration, ?reason:String):js.lib.Promise<PublicThreadChannel<Forum>>;
	function setInvitable(?invitable:Bool, ?reason:String):js.lib.Promise<PublicThreadChannel<Forum>>;
	function setLocked(?locked:Bool, ?reason:String):js.lib.Promise<PublicThreadChannel<Forum>>;
	function setName(name:String, ?reason:String):js.lib.Promise<PublicThreadChannel<Forum>>;
	function setAppliedTags(appliedTags:haxe.ds.ReadOnlyArray<String>, ?reason:String):js.lib.Promise<If<Forum, PublicThreadChannel<Forum>, Any>>;
	function pin(?reason:String):js.lib.Promise<If<Forum, PublicThreadChannel<Forum>, Any>>;
	function unpin(?reason:String):js.lib.Promise<If<Forum, PublicThreadChannel<Forum>, Any>>;
	/**
		Returns a string representation of an object.
	**/
	function toString():Dynamic;
	var id : String;
	final partial : Bool;
	final url : String;
	function fetch(?force:Bool):js.lib.Promise<PublicThreadChannel<Forum>>;
	function isThread():Bool;
	function isTextBased():Bool;
	function isDMBased():Bool;
	function isVoiceBased():Bool;
	function isThreadOnly():Bool;
	function isSendable():Bool;
	final client : Client<Bool>;
	function toJSON(props:haxe.extern.Rest<haxe.DynamicAccess<ts.AnyOf2<String, Bool>>>):Any;
	function valueOf():String;
	var messages : Dynamic;
	var bulkDelete : Dynamic;
	var setRateLimitPerUser : Dynamic;
	var lastMessageId : Dynamic;
	var lastMessage : Dynamic;
	var lastPinTimestamp : Dynamic;
	var lastPinAt : Dynamic;
	var awaitMessageComponent : Dynamic;
	var awaitMessages : Dynamic;
	var createMessageComponentCollector : Dynamic;
	var createMessageCollector : Dynamic;
	var sendTyping : Dynamic;
	var send : Dynamic;
};