package global.three;

@:native("THREE.AnimationAction") extern class AnimationAction {
	function new();
	var loop : AnimationActionLoopStyles;
	var time : Float;
	var timeScale : Float;
	var weight : Float;
	var repetitions : Float;
	var paused : Bool;
	var enabled : Bool;
	var clampWhenFinished : Bool;
	var zeroSlopeAtStart : Bool;
	var zeroSlopeAtEnd : Bool;
	function play(unknown:Dynamic):AnimationAction;
	function stop(unknown:Dynamic):AnimationAction;
	function reset(unknown:Dynamic):AnimationAction;
	function isRunning(unknown:Dynamic):Bool;
	function isScheduled(unknown:Dynamic):Bool;
	function startAt(unknown:Dynamic):AnimationAction;
	function setLoop(unknown:Dynamic):AnimationAction;
	function setEffectiveWeight(unknown:Dynamic):AnimationAction;
	function getEffectiveWeight(unknown:Dynamic):Float;
	function fadeIn(unknown:Dynamic):AnimationAction;
	function fadeOut(unknown:Dynamic):AnimationAction;
	function crossFadeFrom(unknown:Dynamic):AnimationAction;
	function crossFadeTo(unknown:Dynamic):AnimationAction;
	function stopFading(unknown:Dynamic):AnimationAction;
	function setEffectiveTimeScale(unknown:Dynamic):AnimationAction;
	function getEffectiveTimeScale(unknown:Dynamic):Float;
	function setDuration(unknown:Dynamic):AnimationAction;
	function syncWith(unknown:Dynamic):AnimationAction;
	function halt(unknown:Dynamic):AnimationAction;
	function warp(unknown:Dynamic):AnimationAction;
	function stopWarping(unknown:Dynamic):AnimationAction;
	function getMixer(unknown:Dynamic):AnimationMixer;
	function getClip(unknown:Dynamic):AnimationClip;
	function getRoot(unknown:Dynamic):Dynamic;
	static var prototype : AnimationAction;
}