package three;

@:jsRequire("three", "Box3") extern class Box3 {
	function new(unknown:Dynamic);
	var max : Vector3;
	var min : Vector3;
	function set(unknown:Dynamic):Box3;
	function setFromArray(unknown:Dynamic):Box3;
	function setFromPoints(unknown:Dynamic):Box3;
	function setFromCenterAndSize(unknown:Dynamic):Box3;
	function setFromObject(unknown:Dynamic):Box3;
	function clone(unknown:Dynamic):Box3;
	function copy(unknown:Dynamic):Box3;
	function makeEmpty(unknown:Dynamic):Box3;
	function isEmpty(unknown:Dynamic):Bool;
	function getCenter(unknown:Dynamic):Vector3;
	function getSize(unknown:Dynamic):Vector3;
	function expandByPoint(unknown:Dynamic):Box3;
	function expandByVector(unknown:Dynamic):Box3;
	function expandByScalar(unknown:Dynamic):Box3;
	function expandByObject(unknown:Dynamic):Box3;
	function containsPoint(unknown:Dynamic):Bool;
	function containsBox(unknown:Dynamic):Bool;
	function getParameter(unknown:Dynamic):Vector3;
	function intersectsBox(unknown:Dynamic):Bool;
	function intersectsSphere(unknown:Dynamic):Bool;
	function intersectsPlane(unknown:Dynamic):Bool;
	function intersectsTriangle(unknown:Dynamic):Bool;
	function clampPoint(unknown:Dynamic):Vector3;
	function distanceToPoint(unknown:Dynamic):Float;
	function getBoundingSphere(unknown:Dynamic):Sphere;
	function intersect(unknown:Dynamic):Box3;
	function union(unknown:Dynamic):Box3;
	function applyMatrix4(unknown:Dynamic):Box3;
	function translate(unknown:Dynamic):Box3;
	function equals(unknown:Dynamic):Bool;
	function empty(unknown:Dynamic):Dynamic;
	function isIntersectionBox(unknown:Dynamic):Dynamic;
	function isIntersectionSphere(unknown:Dynamic):Dynamic;
	static var prototype : Box3;
}