package ts;

/**
	AnyOf implementation generated by dts2hx
**/
@:transitive extern abstract AnyOf6<T0, T1, T2, T3, T4, T5>(Dynamic) {
	var asType0(get, never) : T0;
	private inline function get_asType0():T0 return this;
	var asType1(get, never) : T1;
	private inline function get_asType1():T1 return this;
	var asType2(get, never) : T2;
	private inline function get_asType2():T2 return this;
	var asType3(get, never) : T3;
	private inline function get_asType3():T3 return this;
	var asType4(get, never) : T4;
	private inline function get_asType4():T4 return this;
	var asType5(get, never) : T5;
	private inline function get_asType5():T5 return this;
}