package node.util;

@:jsRequire("util", "types") @valueModuleOnly extern class Types {
	static function isAnyArrayBuffer(unknown:Dynamic):Bool;
	static function isArgumentsObject(unknown:Dynamic):Bool;
	static function isArrayBuffer(unknown:Dynamic):Bool;
	static function isAsyncFunction(unknown:Dynamic):Bool;
	static function isBooleanObject(unknown:Dynamic):Bool;
	static function isBoxedPrimitive(unknown:Dynamic):Bool;
	static function isDataView(unknown:Dynamic):Bool;
	static function isDate(unknown:Dynamic):Bool;
	static function isExternal(unknown:Dynamic):Bool;
	static function isFloat32Array(unknown:Dynamic):Bool;
	static function isFloat64Array(unknown:Dynamic):Bool;
	static function isGeneratorFunction(unknown:Dynamic):Bool;
	static function isGeneratorObject(unknown:Dynamic):Bool;
	static function isInt8Array(unknown:Dynamic):Bool;
	static function isInt16Array(unknown:Dynamic):Bool;
	static function isInt32Array(unknown:Dynamic):Bool;
	static function isMap(unknown:Dynamic):Bool;
	static function isMapIterator(unknown:Dynamic):Bool;
	static function isNativeError(unknown:Dynamic):Bool;
	static function isNumberObject(unknown:Dynamic):Bool;
	static function isPromise(unknown:Dynamic):Bool;
	static function isProxy(unknown:Dynamic):Bool;
	static function isRegExp(unknown:Dynamic):Bool;
	static function isSet(unknown:Dynamic):Bool;
	static function isSetIterator(unknown:Dynamic):Bool;
	static function isSharedArrayBuffer(unknown:Dynamic):Bool;
	static function isStringObject(unknown:Dynamic):Bool;
	static function isSymbolObject(unknown:Dynamic):Bool;
	static function isTypedArray(unknown:Dynamic):Bool;
	static function isUint8Array(unknown:Dynamic):Bool;
	static function isUint8ClampedArray(unknown:Dynamic):Bool;
	static function isUint16Array(unknown:Dynamic):Bool;
	static function isUint32Array(unknown:Dynamic):Bool;
	static function isWeakMap(unknown:Dynamic):Bool;
	static function isWeakSet(unknown:Dynamic):Bool;
	static function isWebAssemblyCompiledModule(unknown:Dynamic):Bool;
}