package ts;

/**
	AnyOf implementation generated by dts2hx
**/
@:transitive extern abstract AnyOf2<T0, T1>(Dynamic) {
	var asType0(get, never) : T0;
	private inline function get_asType0():T0 return this;
	var asType1(get, never) : T1;
	private inline function get_asType1():T1 return this;
}