package ts;

/**
	AnyOf implementation generated by dts2hx
**/
@:transitive extern abstract AnyOf12<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(Dynamic) {
	var asType0(get, never) : T0;
	private inline function get_asType0():T0 return this;
	var asType1(get, never) : T1;
	private inline function get_asType1():T1 return this;
	var asType2(get, never) : T2;
	private inline function get_asType2():T2 return this;
	var asType3(get, never) : T3;
	private inline function get_asType3():T3 return this;
	var asType4(get, never) : T4;
	private inline function get_asType4():T4 return this;
	var asType5(get, never) : T5;
	private inline function get_asType5():T5 return this;
	var asType6(get, never) : T6;
	private inline function get_asType6():T6 return this;
	var asType7(get, never) : T7;
	private inline function get_asType7():T7 return this;
	var asType8(get, never) : T8;
	private inline function get_asType8():T8 return this;
	var asType9(get, never) : T9;
	private inline function get_asType9():T9 return this;
	var asType10(get, never) : T10;
	private inline function get_asType10():T10 return this;
	var asType11(get, never) : T11;
	private inline function get_asType11():T11 return this;
}