package global._;

typedef LoDashExplicitWrapper<TValue> = {
	@:overload(function<TResult>(unknown:Dynamic):CollectionChain<TResult> { })
	function invokeMap(unknown:Dynamic):CollectionChain<Dynamic>;
	function size(unknown:Dynamic):PrimitiveChain<Float>;
	function now(unknown:Dynamic):PrimitiveChain<Float>;
	function bind(unknown:Dynamic):FunctionChain<(unknown:Dynamic) -> Dynamic>;
	function bindKey(unknown:Dynamic):FunctionChain<(unknown:Dynamic) -> Dynamic>;
	function defer(unknown:Dynamic):PrimitiveChain<Float>;
	function delay(unknown:Dynamic):PrimitiveChain<Float>;
	function wrap<TArgs, TResult>(unknown:Dynamic):FunctionChain<(unknown:Dynamic) -> TResult>;
	function clone(unknown:Dynamic):LoDashExplicitWrapper<TValue>;
	function cloneDeep(unknown:Dynamic):LoDashExplicitWrapper<TValue>;
	@:overload(function(unknown:Dynamic):LoDashExplicitWrapper<TValue> { })
	function cloneDeepWith(unknown:Dynamic):LoDashExplicitWrapper<Dynamic>;
	@:overload(function<TResult>(unknown:Dynamic):ts.AnyOf2<ExpChain<TValue>, ExpChain<TResult>> { })
	@:overload(function(unknown:Dynamic):LoDashExplicitWrapper<TValue> { })
	function cloneWith<TResult>(unknown:Dynamic):ExpChain<TResult>;
	function conformsTo(unknown:Dynamic):PrimitiveChain<Bool>;
	function eq(unknown:Dynamic):PrimitiveChain<Bool>;
	function gt(unknown:Dynamic):PrimitiveChain<Bool>;
	function gte(unknown:Dynamic):PrimitiveChain<Bool>;
	function isArguments(unknown:Dynamic):PrimitiveChain<Bool>;
	function isArray(unknown:Dynamic):PrimitiveChain<Bool>;
	function isArrayBuffer(unknown:Dynamic):PrimitiveChain<Bool>;
	function isArrayLike(unknown:Dynamic):PrimitiveChain<Bool>;
	function isArrayLikeObject(unknown:Dynamic):PrimitiveChain<Bool>;
	function isBoolean(unknown:Dynamic):PrimitiveChain<Bool>;
	function isBuffer(unknown:Dynamic):PrimitiveChain<Bool>;
	function isDate(unknown:Dynamic):PrimitiveChain<Bool>;
	function isElement(unknown:Dynamic):PrimitiveChain<Bool>;
	function isEmpty(unknown:Dynamic):PrimitiveChain<Bool>;
	function isEqual(unknown:Dynamic):PrimitiveChain<Bool>;
	function isEqualWith(unknown:Dynamic):PrimitiveChain<Bool>;
	function isError(unknown:Dynamic):PrimitiveChain<Bool>;
	function isFinite(unknown:Dynamic):PrimitiveChain<Bool>;
	function isFunction(unknown:Dynamic):PrimitiveChain<Bool>;
	function isInteger(unknown:Dynamic):PrimitiveChain<Bool>;
	function isLength(unknown:Dynamic):PrimitiveChain<Bool>;
	function isMap(unknown:Dynamic):PrimitiveChain<Bool>;
	function isMatch(unknown:Dynamic):PrimitiveChain<Bool>;
	function isMatchWith(unknown:Dynamic):PrimitiveChain<Bool>;
	function isNaN(unknown:Dynamic):PrimitiveChain<Bool>;
	function isNative(unknown:Dynamic):PrimitiveChain<Bool>;
	function isNil(unknown:Dynamic):PrimitiveChain<Bool>;
	function isNull(unknown:Dynamic):PrimitiveChain<Bool>;
	function isNumber(unknown:Dynamic):PrimitiveChain<Bool>;
	function isObject(unknown:Dynamic):PrimitiveChain<Bool>;
	function isObjectLike(unknown:Dynamic):PrimitiveChain<Bool>;
	function isPlainObject(unknown:Dynamic):PrimitiveChain<Bool>;
	function isRegExp(unknown:Dynamic):PrimitiveChain<Bool>;
	function isSafeInteger(unknown:Dynamic):PrimitiveChain<Bool>;
	function isSet(unknown:Dynamic):PrimitiveChain<Bool>;
	function isString(unknown:Dynamic):PrimitiveChain<Bool>;
	function isSymbol(unknown:Dynamic):PrimitiveChain<Bool>;
	function isTypedArray(unknown:Dynamic):PrimitiveChain<Bool>;
	function isUndefined(unknown:Dynamic):PrimitiveChain<Bool>;
	function isWeakMap(unknown:Dynamic):PrimitiveChain<Bool>;
	function isWeakSet(unknown:Dynamic):PrimitiveChain<Bool>;
	function lt(unknown:Dynamic):PrimitiveChain<Bool>;
	function lte(unknown:Dynamic):PrimitiveChain<Bool>;
	function toFinite(unknown:Dynamic):PrimitiveChain<Float>;
	function toInteger(unknown:Dynamic):PrimitiveChain<Float>;
	function toLength(unknown:Dynamic):PrimitiveChain<Float>;
	function toNumber(unknown:Dynamic):PrimitiveChain<Float>;
	function toPlainObject(unknown:Dynamic):ObjectChain<Dynamic>;
	function toSafeInteger(unknown:Dynamic):PrimitiveChain<Float>;
	function add(unknown:Dynamic):PrimitiveChain<Float>;
	function ceil(unknown:Dynamic):PrimitiveChain<Float>;
	function divide(unknown:Dynamic):PrimitiveChain<Float>;
	function floor(unknown:Dynamic):PrimitiveChain<Float>;
	function mean(unknown:Dynamic):PrimitiveChain<Float>;
	function multiply(unknown:Dynamic):PrimitiveChain<Float>;
	function round(unknown:Dynamic):PrimitiveChain<Float>;
	function subtract(unknown:Dynamic):PrimitiveChain<Float>;
	function sum(unknown:Dynamic):PrimitiveChain<Float>;
	@:overload(function(unknown:Dynamic):PrimitiveChain<Float> { })
	function clamp(unknown:Dynamic):PrimitiveChain<Float>;
	function inRange(unknown:Dynamic):PrimitiveChain<Bool>;
	@:overload(function(unknown:Dynamic):PrimitiveChain<Float> { })
	function random(unknown:Dynamic):PrimitiveChain<Float>;
	function entries(unknown:Dynamic):CollectionChain<ts.Tuple2<String, Dynamic>>;
	function entriesIn(unknown:Dynamic):CollectionChain<ts.Tuple2<String, Dynamic>>;
	function findKey(unknown:Dynamic):StringNullableChain;
	function findLastKey(unknown:Dynamic):StringNullableChain;
	function forIn(unknown:Dynamic):LoDashExplicitWrapper<TValue>;
	function forInRight(unknown:Dynamic):LoDashExplicitWrapper<TValue>;
	function forOwn(unknown:Dynamic):LoDashExplicitWrapper<TValue>;
	function forOwnRight(unknown:Dynamic):LoDashExplicitWrapper<TValue>;
	function functions(unknown:Dynamic):CollectionChain<String>;
	function functionsIn(unknown:Dynamic):CollectionChain<String>;
	function has(unknown:Dynamic):PrimitiveChain<Bool>;
	function hasIn(unknown:Dynamic):PrimitiveChain<Bool>;
	function invert(unknown:Dynamic):ObjectChain<Dictionary<String>>;
	function invoke(unknown:Dynamic):LoDashExplicitWrapper<Dynamic>;
	function keys(unknown:Dynamic):CollectionChain<String>;
	function keysIn(unknown:Dynamic):CollectionChain<String>;
	function result<TResult>(unknown:Dynamic):ExpChain<TResult>;
	@:overload(function<TResult>(unknown:Dynamic):ExpChain<TResult> { })
	function set(unknown:Dynamic):LoDashExplicitWrapper<TValue>;
	@:overload(function<TResult>(unknown:Dynamic):ExpChain<TResult> { })
	function setWith(unknown:Dynamic):LoDashExplicitWrapper<TValue>;
	function toPairs(unknown:Dynamic):CollectionChain<ts.Tuple2<String, Dynamic>>;
	function toPairsIn(unknown:Dynamic):CollectionChain<ts.Tuple2<String, Dynamic>>;
	function unset(unknown:Dynamic):PrimitiveChain<Bool>;
	function update(unknown:Dynamic):ObjectChain<Dynamic>;
	function chain(unknown:Dynamic):LoDashExplicitWrapper<TValue>;
	function commit(unknown:Dynamic):LoDashExplicitWrapper<TValue>;
	function plant(unknown:Dynamic):LoDashExplicitWrapper<TValue>;
	function reverse(unknown:Dynamic):LoDashExplicitWrapper<TValue>;
	function toJSON(unknown:Dynamic):TValue;
	function value(unknown:Dynamic):TValue;
	function valueOf(unknown:Dynamic):TValue;
	function tap(unknown:Dynamic):LoDashExplicitWrapper<TValue>;
	function thru<TResult>(unknown:Dynamic):ExpChain<TResult>;
	function camelCase(unknown:Dynamic):StringChain<String>;
	function capitalize(unknown:Dynamic):StringChain<Dynamic>;
	function deburr(unknown:Dynamic):StringChain<String>;
	function endsWith(unknown:Dynamic):PrimitiveChain<Bool>;
	function escape(unknown:Dynamic):StringChain<String>;
	function escapeRegExp(unknown:Dynamic):StringChain<String>;
	function kebabCase(unknown:Dynamic):StringChain<String>;
	function lowerCase(unknown:Dynamic):StringChain<String>;
	function lowerFirst(unknown:Dynamic):StringChain<Dynamic>;
	function pad(unknown:Dynamic):StringChain<String>;
	function padEnd(unknown:Dynamic):StringChain<String>;
	function padStart(unknown:Dynamic):StringChain<String>;
	function parseInt(unknown:Dynamic):PrimitiveChain<Float>;
	function repeat(unknown:Dynamic):StringChain<String>;
	@:overload(function(unknown:Dynamic):StringChain<String> { })
	function replace(unknown:Dynamic):StringChain<String>;
	function snakeCase(unknown:Dynamic):StringChain<String>;
	function split(unknown:Dynamic):CollectionChain<String>;
	function startCase(unknown:Dynamic):StringChain<String>;
	function startsWith(unknown:Dynamic):PrimitiveChain<Bool>;
	function template(unknown:Dynamic):FunctionChain<TemplateExecutor>;
	function toLower(unknown:Dynamic):StringChain<Dynamic>;
	function toUpper(unknown:Dynamic):StringChain<Dynamic>;
	function trim(unknown:Dynamic):StringChain<String>;
	function trimEnd(unknown:Dynamic):StringChain<String>;
	function trimStart(unknown:Dynamic):StringChain<String>;
	function truncate(unknown:Dynamic):StringChain<String>;
	function unescape(unknown:Dynamic):StringChain<String>;
	function upperCase(unknown:Dynamic):StringChain<String>;
	function upperFirst(unknown:Dynamic):StringChain<Dynamic>;
	function words(unknown:Dynamic):CollectionChain<String>;
	function attempt<TResult>(unknown:Dynamic):ts.AnyOf2<ObjectChain<js.lib.Error>, ExpChain<TResult>>;
	function bindAll(unknown:Dynamic):LoDashExplicitWrapper<TValue>;
	function conforms(unknown:Dynamic):FunctionChain<(unknown:Dynamic) -> Bool>;
	function constant(unknown:Dynamic):FunctionChain<(unknown:Dynamic) -> TValue>;
	@:overload(function<TDefault>(unknown:Dynamic):ExpChain<Dynamic> { })
	function defaultTo(unknown:Dynamic):ExpChain<TValue>;
	function identity(unknown:Dynamic):LoDashExplicitWrapper<TValue>;
	function matches<V>(unknown:Dynamic):FunctionChain<(unknown:Dynamic) -> Bool>;
	@:overload(function<SrcValue, Value>(unknown:Dynamic):FunctionChain<(unknown:Dynamic) -> Bool> { })
	function matchesProperty<SrcValue>(unknown:Dynamic):FunctionChain<(unknown:Dynamic) -> Bool>;
	function method(unknown:Dynamic):FunctionChain<(unknown:Dynamic) -> Dynamic>;
	function methodOf(unknown:Dynamic):LoDashExplicitWrapper<(unknown:Dynamic) -> Dynamic>;
	@:overload(function(unknown:Dynamic):LoDashExplicitWrapper<LoDashStatic> { })
	function mixin(unknown:Dynamic):LoDashExplicitWrapper<TValue>;
	function noConflict(unknown:Dynamic):LoDashExplicitWrapper<LoDashStatic>;
	function noop(unknown:Dynamic):PrimitiveChain<Null<Any>>;
	function nthArg(unknown:Dynamic):FunctionChain<(unknown:Dynamic) -> Dynamic>;
	function property<TObj, TResult>(unknown:Dynamic):FunctionChain<(unknown:Dynamic) -> TResult>;
	function propertyOf(unknown:Dynamic):LoDashExplicitWrapper<(unknown:Dynamic) -> Dynamic>;
	function range(unknown:Dynamic):CollectionChain<Float>;
	function rangeRight(unknown:Dynamic):CollectionChain<Float>;
	function stubArray(unknown:Dynamic):CollectionChain<Dynamic>;
	@:overload(function(unknown:Dynamic):LoDashExplicitWrapper<Bool> { })
	function stubFalse(unknown:Dynamic):PrimitiveChain<Bool>;
	function stubObject(unknown:Dynamic):LoDashExplicitWrapper<Dynamic>;
	function stubString(unknown:Dynamic):StringChain<String>;
	@:overload(function(unknown:Dynamic):LoDashExplicitWrapper<Bool> { })
	function stubTrue(unknown:Dynamic):PrimitiveChain<Bool>;
	@:overload(function(unknown:Dynamic):CollectionChain<Float> { })
	function times<TResult>(unknown:Dynamic):CollectionChain<TResult>;
	function toPath(unknown:Dynamic):CollectionChain<String>;
	function uniqueId(unknown:Dynamic):StringChain<String>;
};