package discord_api_types.v10;

typedef APIDMInteraction = ts.AnyOf7<APIChatInputApplicationCommandDMInteraction, APIUserApplicationCommandDMInteraction, APIMessageApplicationCommandDMInteraction, APIPrimaryEntryPointCommandDMInteraction, APIApplicationCommandAutocompleteDMInteraction, APIMessageComponentDMInteraction, APIModalSubmitDMInteraction>;