package discord_api_types.v10;

typedef GatewayMessageCreateDispatchData = {
	/**
		ID of the guild the message was sent in
	**/
	@:optional
	var guild_id : String;
	/**
		Member properties for this message's author
		
		The member object exists in `MESSAGE_CREATE` and `MESSAGE_UPDATE` events
		from text-based guild channels
	**/
	@:optional
	var member : APIGuildMemberNoUser;
	/**
		Users specifically mentioned in the message
	**/
	var mentions : Array<APIUserWithMember>;
	/**
		ID of the channel the message was sent in
	**/
	var channel_id : String;
	/**
		ID of the message
	**/
	var id : String;
	/**
		The author of this message (only a valid user in the case where the message is generated by a user or bot user)
		
		If the message is generated by a webhook, the author object corresponds to the webhook's id,
		username, and avatar. You can tell if a message is generated by a webhook by checking for the `webhook_id` property
	**/
	var author : APIUser;
	/**
		Contents of the message
		
		The `MESSAGE_CONTENT` privileged gateway intent is required for verified applications to receive a non-empty value from this field
		
		In the Discord Developers Portal, you need to enable the toggle of this intent of your application in **Bot \> Privileged Gateway Intents**.
		You also need to specify the intent bit value (`1 << 15`) if you are connecting to the gateway
	**/
	var content : String;
	/**
		When this message was sent
	**/
	var timestamp : String;
	/**
		When this message was edited (or null if never)
	**/
	var edited_timestamp : Null<String>;
	/**
		Whether this was a TTS message
	**/
	var tts : Bool;
	/**
		Whether this message mentions everyone
	**/
	var mention_everyone : Bool;
	/**
		Roles specifically mentioned in this message
	**/
	var mention_roles : Array<String>;
	/**
		Channels specifically mentioned in this message
		
		Not all channel mentions in a message will appear in `mention_channels`.
		- Only textual channels that are visible to everyone in a lurkable guild will ever be included
		- Only crossposted messages (via Channel Following) currently include `mention_channels` at all
		
		If no mentions in the message meet these requirements, this field will not be sent
	**/
	@:optional
	var mention_channels : Array<APIChannelMention>;
	/**
		Any attached files
	**/
	var attachments : Array<APIAttachment>;
	/**
		Any embedded content
	**/
	var embeds : Array<APIEmbed>;
	/**
		Reactions to the message
	**/
	@:optional
	var reactions : Array<APIReaction>;
	/**
		A nonce that can be used for optimistic message sending (up to 25 characters)
		
		**You will not receive this from further fetches. This is received only once from a `MESSAGE_CREATE`
		event to ensure it got sent**
	**/
	@:optional
	var nonce : ts.AnyOf2<String, Float>;
	/**
		Whether this message is pinned
	**/
	var pinned : Bool;
	/**
		If the message is generated by a webhook, this is the webhook's id
	**/
	@:optional
	var webhook_id : String;
	/**
		Type of message
	**/
	var type : MessageType;
	/**
		Sent with Rich Presence-related chat embeds
	**/
	@:optional
	var activity : APIMessageActivity;
	/**
		Sent with Rich Presence-related chat embeds
	**/
	@:optional
	var application : {
		/**
			The id of the app
		**/
		@:optional
		var id : Dynamic;
		/**
			The name of the app
		**/
		@:optional
		var name : Dynamic;
		/**
			The icon hash of the app
		**/
		@:optional
		var icon : Dynamic;
		/**
			The description of the app
		**/
		@:optional
		var description : Dynamic;
		/**
			An array of rpc origin urls, if rpc is enabled
		**/
		@:optional
		var rpc_origins : Dynamic;
		/**
			When `false` only app owner can join the app's bot to guilds
		**/
		@:optional
		var bot_public : Dynamic;
		/**
			When `true` the app's bot will only join upon completion of the full oauth2 code grant flow
		**/
		@:optional
		var bot_require_code_grant : Dynamic;
		/**
			Partial user object for the bot user associated with the application
		**/
		@:optional
		var bot : Dynamic;
		/**
			The url of the application's terms of service
		**/
		@:optional
		var terms_of_service_url : Dynamic;
		/**
			The url of the application's privacy policy
		**/
		@:optional
		var privacy_policy_url : Dynamic;
		/**
			Partial user object containing info on the owner of the application
		**/
		@:optional
		var owner : Dynamic;
		/**
			An empty string
		**/
		@:optional
		var summary : Dynamic;
		/**
			The hexadecimal encoded key for verification in interactions and the GameSDK's GetTicket function
		**/
		@:optional
		var verify_key : Dynamic;
		/**
			The team this application belongs to
		**/
		@:optional
		var team : Dynamic;
		/**
			If this application is a game sold on Discord, this field will be the guild to which it has been linked
		**/
		@:optional
		var guild_id : Dynamic;
		/**
			A partial object of the associated guild
		**/
		@:optional
		var guild : Dynamic;
		/**
			If this application is a game sold on Discord, this field will be the id of the "Game SKU" that is created, if exists
		**/
		@:optional
		var primary_sku_id : Dynamic;
		/**
			If this application is a game sold on Discord, this field will be the URL slug that links to the store page
		**/
		@:optional
		var slug : Dynamic;
		/**
			If this application is a game sold on Discord, this field will be the hash of the image on store embeds
		**/
		@:optional
		var cover_image : Dynamic;
		/**
			The application's public flags
		**/
		@:optional
		var flags : Dynamic;
		/**
			Approximate count of guilds the application has been added to
		**/
		@:optional
		var approximate_guild_count : Dynamic;
		/**
			Approximate count of users that have installed the app (authorized with `application.commands` as a scope)
		**/
		@:optional
		var approximate_user_install_count : Dynamic;
		/**
			Approximate count of users that have OAuth2 authorizations for the app
		**/
		@:optional
		var approximate_user_authorization_count : Dynamic;
		/**
			Array of redirect URIs for the application
		**/
		@:optional
		var redirect_uris : Dynamic;
		/**
			The interactions endpoint URL for the application
		**/
		@:optional
		var interactions_endpoint_url : Dynamic;
		/**
			The application's role connection verification entry point,
			which when configured will render the app as a verification method in the guild role verification configuration
		**/
		@:optional
		var role_connections_verification_url : Dynamic;
		/**
			Up to 5 tags of max 20 characters each describing the content and functionality of the application
		**/
		@:optional
		var tags : Dynamic;
		/**
			Settings for the application's default in-app authorization link, if enabled
		**/
		@:optional
		var install_params : Dynamic;
		/**
			Default scopes and permissions for each supported installation context. Value for each key is an integration type configuration object
		**/
		@:optional
		var integration_types_config : Dynamic;
		/**
			The application's default custom authorization link, if enabled
		**/
		@:optional
		var custom_install_url : Dynamic;
		/**
			Event webhook URL for the app to receive webhook events
		**/
		@:optional
		var event_webhooks_url : Dynamic;
		/**
			If webhook events are enabled for the app
		**/
		@:optional
		var event_webhooks_status : Dynamic;
		/**
			List of webhook event types the app subscribes to
		**/
		@:optional
		var event_webhooks_types : Dynamic;
	};
	/**
		If the message is a response to an Interaction, this is the id of the interaction's application
	**/
	@:optional
	var application_id : String;
	/**
		Reference data sent with crossposted messages, replies, pins, and thread starter messages
	**/
	@:optional
	var message_reference : APIMessageReference;
	/**
		Message flags combined as a bitfield
	**/
	@:optional
	var flags : MessageFlags;
	/**
		The message associated with the `message_reference`
		
		This field is only returned for messages with a `type` of `19` (REPLY).
		
		If the message is a reply but the `referenced_message` field is not present,
		the backend did not attempt to fetch the message that was being replied to,
		so its state is unknown.
		
		If the field exists but is `null`, the referenced message was deleted
	**/
	@:optional
	var referenced_message : APIMessage;
	/**
		Sent if the message is sent as a result of an interaction
	**/
	@:optional
	var interaction_metadata : APIMessageInteractionMetadata;
	/**
		Sent if the message is a response to an Interaction
	**/
	@:optional
	var interaction : APIMessageInteraction;
	/**
		Sent if a thread was started from this message
	**/
	@:optional
	var thread : APIChannel;
	/**
		Sent if the message contains components like buttons, action rows, or other interactive components
		
		The `MESSAGE_CONTENT` privileged gateway intent is required for verified applications to receive a non-empty value from this field
		
		In the Discord Developers Portal, you need to enable the toggle of this intent of your application in **Bot \> Privileged Gateway Intents**.
		You also need to specify the intent bit value (`1 << 15`) if you are connecting to the gateway
	**/
	@:optional
	var components : Array<APIMessageTopLevelComponent>;
	/**
		Sent if the message contains stickers
	**/
	@:optional
	var sticker_items : Array<{
		/**
			Name of the sticker
		**/
		var name : Dynamic;
		/**
			ID of the sticker
		**/
		var id : Dynamic;
		/**
			Type of sticker format
		**/
		var format_type : Dynamic;
	}>;
	/**
		The stickers sent with the message
	**/
	@:optional
	var stickers : Array<APISticker>;
	/**
		A generally increasing integer (there may be gaps or duplicates) that represents the approximate position of the message in a thread
		
		It can be used to estimate the relative position of the message in a thread in company with `total_message_sent` on parent thread
	**/
	@:optional
	var position : Float;
	/**
		Data of the role subscription purchase or renewal that prompted this `ROLE_SUBSCRIPTION_PURCHASE` message
	**/
	@:optional
	var role_subscription_data : APIMessageRoleSubscriptionData;
	/**
		Data for users, members, channels, and roles in the message's auto-populated select menus
	**/
	@:optional
	var resolved : APIInteractionDataResolved;
	/**
		A poll!
		
		The `MESSAGE_CONTENT` privileged gateway intent is required for verified applications to receive a non-empty value from this field
		
		In the Discord Developers Portal, you need to enable the toggle of this intent of your application in **Bot \> Privileged Gateway Intents**.
		You also need to specify the intent bit value (`1 << 15`) if you are connecting to the gateway
	**/
	@:optional
	var poll : APIPoll;
	/**
		The message associated with the message_reference. This is a minimal subset of fields in a message (e.g. author is excluded.)
	**/
	@:optional
	var message_snapshots : Array<APIMessageSnapshot>;
	/**
		The call associated with the message
	**/
	@:optional
	var call : APIMessageCall;
};