package ts;

/**
	AnyOf implementation generated by dts2hx
**/
@:transitive extern abstract AnyOf3<T0, T1, T2>(Dynamic) {
	var asType0(get, never) : T0;
	private inline function get_asType0():T0 return this;
	var asType1(get, never) : T1;
	private inline function get_asType1():T1 return this;
	var asType2(get, never) : T2;
	private inline function get_asType2():T2 return this;
}